import { StyleSheet, Platform } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
  },
  scrollView: {
    flex: 1,
  },
  scrollViewContent: {
    paddingBottom: 32,
  },
  scrollViewWithCookieNotice: {
    paddingBottom: 80,
  },
  heroSection: {
    padding: 24,
    paddingTop: 40,
    paddingBottom: 40,
  },
  heroContent: {
    alignItems: 'flex-start',
    maxWidth: 800,
    marginHorizontal: 'auto',
  },
  heroTagline: {
    fontSize: 32,
    fontWeight: 'bold',
    color: '#FFFFFF',
    textAlign: 'left',
    marginBottom: 16,
  },
  heroSubtitle: {
    fontSize: 16,
    color: 'rgba(255, 255, 255, 0.9)',
    marginBottom: 24,
    textAlign: 'left',
    maxWidth: 500,
  },
  heroMetric: {
    alignItems: 'flex-start',
    marginTop: 16,
    marginBottom: 24,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    padding: 16,
    borderRadius: 8,
    width: '100%',
    maxWidth: 400,
  },
  heroMetricValue: {
    fontSize: 36,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  heroMetricLabel: {
    fontSize: 14,
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 4,
  },
  assessmentButtonContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    width: '100%',
  },
  assessmentButton: {
    width: '100%',
    maxWidth: 320,
    marginVertical: 8,
    alignSelf: 'center',
    ...Platform.select({
      android: { elevation: 4 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      web: { boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.15)' },
    }),
  },
  section: {
    marginTop: 24,
    marginHorizontal: 16,
    marginBottom: 16,
  },
  sectionTitle: {
    fontSize: 14,
    fontWeight: '500',
    marginBottom: 12,
    marginLeft: 8,
    letterSpacing: 0.1,
    textTransform: 'uppercase',
  },
  card: {
    borderRadius: 12,
    ...Platform.select({
      android: { elevation: 2 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 3,
      },
      web: { boxShadow: '0px 1px 3px rgba(0, 0, 0, 0.1)' },
    }),
  },
  challengeItem: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 8,
  },
  iconContainer: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 16,
  },
  challengeTextContainer: { flex: 1 },
  challengeTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 4,
  },
  challengeDescription: { fontSize: 14 },
  divider: { marginVertical: 12 },
  testimonial: {
    fontSize: 16,
    fontStyle: 'italic',
    marginBottom: 12,
    lineHeight: 24,
  },
  testimonialAuthor: { fontSize: 14, textAlign: 'right' },
  ctaCard: {
    borderRadius: 12,
    padding: 8,
    ...Platform.select({
      android: { elevation: 4 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      web: { boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.15)' },
    }),
  },
  ctaTitle: { fontSize: 20, fontWeight: 'bold', marginBottom: 8 },
  ctaDescription: { fontSize: 16, marginBottom: 16 },
  footer: {
    marginTop: 48,
    marginBottom: 24,
    paddingHorizontal: 16,
    alignItems: 'center',
  },
  footerDivider: {
    height: 1,
    width: '100%',
    marginBottom: 24,
  },
  footerLinks: { flexDirection: 'row', justifyContent: 'center', alignItems: 'center' },
  footerLink: { fontSize: 14, padding: 4 },
  footerLinkDivider: { fontSize: 14, marginHorizontal: 8 },
  footerCopyright: { fontSize: 14, fontWeight: '500', marginBottom: 8 },
  footerAddress: { fontSize: 14, marginBottom: 16 },
  modalSafeArea: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)' },
  centeredView: { flex: 1, justifyContent: 'center', alignItems: 'center', padding: 10 },
  modalView: {
    width: '100%',
    maxHeight: '90%',
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    overflow: 'hidden',
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 15,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E5E5',
    width: '100%',
  },
  modalTitle: { fontSize: 18, fontWeight: 'bold' },
  closeButton: {
    padding: 5,
    width: 44,
    height: 44,
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 10,
  },
  modalScrollView: { width: '100%' },
  modalScrollViewContent: { padding: 16 },
  modalText: { fontSize: 14, lineHeight: 20, marginBottom: 10 },
  modalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  modalContent: {
    width: '90%',
    maxWidth: 400,
    maxHeight: '90%',
    backgroundColor: 'white',
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 4,
    elevation: 5,
    overflow: 'hidden',
    padding: 16,
  },
  submitButton: {
    paddingVertical: 0,
    paddingHorizontal: 0,
    borderRadius: 9999, // Pill shape for modal submit
    minWidth: 240,
    minHeight: 60,
    width: '100%',
    maxWidth: 320,
    marginTop: 24,
    alignSelf: 'center',
    justifyContent: 'center',
    borderWidth: 0,
    ...Platform.select({
      android: { elevation: 4 },
      ios: {
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
      },
      web: { boxShadow: '0px 2px 8px rgba(0, 0, 0, 0.15)' },
    }),
  },
  downloadButton: {
    marginTop: 8,
    width: '100%',
    borderRadius: 9999, // Pill shape for modal close
  },
  input: {
    borderWidth: StyleSheet.hairlineWidth,
    borderRadius: 4,
    padding: 12,
    marginBottom: 16,
    width: '100%',
  },
  errorText: {
    marginBottom: 16,
    fontSize: 14,
  },
  successContainer: {
    alignItems: 'center',
    marginTop: 8,
  },
  successText: {
    fontSize: 16,
    marginBottom: 16,
    textAlign: 'center',
  },
});
